DROP TABLE IF EXISTS "user_wallets";
DROP TABLE IF EXISTS "user_stock_balances";
DROP TABLE IF EXISTS "trades";
DROP TABLE IF EXISTS "orders";
DROP TABLE IF EXISTS "stocks";
DROP TABLE IF EXISTS "tokens";
DROP TABLE IF EXISTS "users";
